name: Integracion continua

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  ci_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.1
      - run: npm ci
      - run: npm test
      - run: npm run build
        env:
          MONGODB_URI: mongodb+srv://Cristh:WinterHat@cluster-ct.aqcqb.mongodb.net/ct-database?retryWrites=true&w=majority
  